# Discord Bot Token
# From your application at discord.com/developers
BotToken: "BOT_TOKEN_HERE"

# Discord Application Commands
ApplicationCommands:
  Enabled: true

# Account Linking configuration
AccountLinking:
  Enabled: true

  # The maximum number of accounts a single discord user can link
  MaxAccounts: 1

  # If account linking should modify the whitelist
  ModifiesWhitelist: true


# Minecraft/Discord bidirectional chat relay
ChatRelay:
  Enabled: true

  # Channel IDs
  Channels:
    Chat: [
      "000000000000000000"
    ]
    Console: "000000000000000000"

  # Whether to relay messages from different guilds
  DiscordToDiscord:
    Enabled: true
    ShowServerProfile: true


  # The bot will send messages using webhooks, if disabled, will fall back to 'MessageFormat' below
  #   %name%
  #   %username%
  #   %message%
  WebhookMessages:
    Enabled: true
    # Username to use for minecraft chat messages
    UsernameFormat: "%username%"
    # Message format to use for minecraft chat messages
    ContentFormat: "%message%"
    # Whether to use linked discord account username
    #UsernameFromDiscord: false
    # Whether to use linked discord account avatar
    #AvatarFromDiscord: false
    # If not, URL to fetch avatar
    AvatarURL: "https://mc-heads.net/avatar/%username%"

  # Messages Formatting
  MessageFormat:

    # Discord -> Minecraft
    DiscordToMinecraft:

      # Chat - A Message sent into the Discord 'Chat' channel.
      # Available placeholders:
      #   %name%      Discord users display name
      #   %username%  Discord users username
      #   %message%   The message content
      #   %channel%   The channel the message was sent from
      #   %guild%     The name of the server the message was sent from
      Chat: "&9&l[Discord | %guild%]&r %username% > &7%message%"

    # Minecraft -> Discord
    MinecraftToDiscord:

      # Player Events
      # Available placeholders for all nested
      #   %name%:         display name from things like nicknames
      #   %username%:            raw player username
      PlayerEvents:

        # Chat - A message sent into the Minecraft chat by a player.
        # Available placeholders:
        #   %message%   The message content
        #   %world%     The world the message was sent from
        Chat:
          Content: "**%username% >** %message%"
          Embed:
            Enabled: false
            Title: ""
            Description: ""
            Color: "#000000"
            Author:
              Name: ""
              IconURL: ""
            Footer:
              Text: ""
              IconURL: ""
            ThumbnailURL: ""

        # Death - A player death
        # Available placeholders:
        #   %message%   The death message (includes username)
        #   %world%     The world the player died in
        Death:
          Content: "## :skull: %message%"
          Embed:
            Enabled: false
            Title: ""
            Description: ""
            Color: "#000000"
            Author:
              Name: ""
              IconURL: ""
            Footer:
              Text: ""
              IconURL: ""
            ThumbnailURL: ""

        # Join - A player joining the server
        # Available placeholders:
        #   %message%   The join message
        Join:
          Content: ""
          Embed:
            Enabled: true
            Title: ""
            Description: ""
            Color: "#00FF00"
            Author:
              Name: "%username% joined the server"
              IconURL: "https://mc-heads.net/avatar/%username%"
            Footer:
              Text: ""
              IconURL: ""
            ThumbnailURL: ""

        # Leave - A player leaving the server
        # Available placeholders:
        #   %message%   The leave message
        Leave:
          Content: ""
          Embed:
            Enabled: true
            Title: ""
            Description: ""
            Color: "#FF0000"
            Author:
              Name: "%username% left the server"
              IconURL: "https://mc-heads.net/avatar/%username%"
            Footer:
              Text: ""
              IconURL: ""
            ThumbnailURL: ""

        # Advancement - A player earning an advancement
        # Available placeholders:
        #   %title%         The advancement title
        #   %description%   The advancement description
        Advancement:
          Content: "### :trophy: %username% has made the advancement ***%title%*** \n- %description%"
          Embed:
            Enabled: false
            Title: ""
            Description: "%title%"
            Color: "#FF00FF"
            Author:
              Name: "%username% made an advancement"
              IconURL: "https://mc-heads.net/avatar/%username%"
            Footer:
              Text: ""
              IconURL: ""
            ThumbnailURL: ""

      # Server Events
      ServerEvents:

        Startup:
          Content: "# :white_check_mark: Server has started."
          Embed:
            Enabled: false
            Title: ""
            Description: ""
            Color: "#000000"
            Author:
              Name: ""
              IconURL: ""
            Footer:
              Text: ""
              IconURL: ""
            ThumbnailURL: ""

        Stop:
          Content: "# :octagonal_sign: Server has stopped."
          Embed:
            Enabled: false
            Title: ""
            Description: ""
            Color: "#000000"
            Author:
              Name: ""
              IconURL: ""
            Footer:
              Text: ""
              IconURL: ""
            ThumbnailURL: ""